[phases.setup]
nixPkgs = ['python310', 'python310Packages.distutils-extra', 'python310Packages.pip', 'python310Packages.setuptools', 'python310Packages.wheel']

[phases.install]
cmds = ['python -m venv /opt/venv', '. /opt/venv/bin/activate && pip install wheel setuptools && pip install -r requirements.txt']